### PR TITLE
Port to Rust

### PR DESCRIPTION
**Pull request by Yoplitein**
As it says on the tin :^)

Would you be interested in registering a crates.io package? If so, I would be happy to sort out the `Cargo.toml` to allow it.

### CODE REVIEW

**Comment by KdotJPG** [comment]
This looks great, thanks for making the port!

I do slightly prefer organizing the gradient tables with all components of the same vector on the same line, since it's an alternative to multidimensional arrays / arrays of dedicated vector types that enables a few manual optimizations, but if I decide I care enough I can just make a follow-up commit.

Also good catch on the unused constant `SEED_FLIP_3D` in the 2S noise. It looks like that's supposed to go on line 291: https://github.com/KdotJPG/OpenSimplex2/pull/19/files#diff-d8f56b5dd942dec29805de8d99e9f47686baf2c2efaf284ee5685af960a7afd6R291 but I forgot to replace the magic number.

And yes to `Cargo.toml` + making a creates.io package, I would very much appreciate the contributions there. 👍

**Comment by Yoplitein** [comment]
That should do it.

I'm not sure whether crates.io verifies repo ownership or the like, but once merged I can certainly give it a shot. 😄

**Comment by KdotJPG** [comment]
Oh nice, thanks for doing all of that! I suppose there's a technical (rather, namespace-path-related reason) for naming them `fast` and `smooth` rather than `opensimplex2` and `opensimplex2s`?

(Last question before merging!)

**Comment by Yoplitein** [comment]
Indeed, top-level modules ("crates" in Rust parlance) can only be created by way of a new package (at least in the cargo ecosystem.) So the qualified path would have been `opensimplex2::opensimplex2s::noise2`, etc.

**Comment by KdotJPG** [comment]
Works for me!

Thanks so much for the contributions!

**Comment by Yoplitein** [comment]
Cheers! I was able to publish [the crates.io package](https://crates.io/crates/opensimplex2) without issue, too. :tada:

Allow me to thank you in kind for all your hard work on this fine algorithm. I just hope this helps get it into more people's hands. :smile:

**Pull request merged**
